apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: amq-mtl
  application: amq-mtl
  namespace: amq-mtl
spec:
  acceptors:
    - port: 61616
      expose: true
      multicastPrefix: jms.topic.
      name: all
      connectionsAllowed: 10
      enabledProtocols: all
      protocols: all
      anycastPrefix: jms.queue.
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  console:
    expose: true
  adminUser: admin

---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: demo1
  namespace: amq-mtl
spec:
  addressName: demo1
  queueName: demo1
  routingType: anycast

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: amq-mtl
spec:
  to:
    kind: Service
    name: amq-mtl-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None