apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  namespace: amq-lvl
  name: amq-lvl
spec:
  acceptors:
    - port: 61616
      verifyHost: false
      expose: true
      name: all
      connectionsAllowed: 10
      enabledProtocols: all
      protocols: all
      anycastPrefix: jms.queue.
      multicastPrefix: jms.topic.
  adminPassword: admin
  deploymentPlan:
    size: 3
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
    clustered: true
  brokerProperties:
   - "AMQPConnections.target.uri=tcp://amq-mtl-all-${STATEFUL_SET_ORDINAL}-svc.amq-mtl.svc.cluster.local:61616?clientFailureCheckPeriod=2000&connectionTTL=5000"
   - "AMQPConnections.target.retryInterval=5000"
   - "AMQPConnections.target.reconnect-attempts=-1"
   - "AMQPConnections.target.user=admin"
   - "AMQPConnections.target.password=admin"
   - "AMQPConnections.target.autoStart=true"
   - "AMQPConnections.target.connectionElements.mirror.type=MIRROR"
   - "AMQPConnections.target.connectionElements.mirror.messageAcknowledgements=true"
   - "AMQPConnections.target.connectionElements.mirror.queueCreation=true"
   - "AMQPConnections.target.connectionElements.mirror.queueRemoval=true"
   - "clusterConfiguration.amq-lvl.name=amq-lvl"
   - "clusterConfigurations.amq-lvl.messageLoadBalancingType=OFF_WITH_REDISTRIBUTION"
  console:
    expose: true
  adminUser: admin

---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: demo1
  namespace: amq-lvl
spec:
  addressName: demo1
  queueName: demo1
  routingType: anycast

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: amq-lvl
spec:
  to:
    kind: Service
    name: amq-lvl-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None