apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  namespace: amq-lvl
  name: amq-lvl
  application: aqm-lvl
spec:
  acceptors:
    - port: 61616
      verifyHost: false
      expose: true
      multicastPrefix: jms.topic.
      name: all
      connectionsAllowed: 10
      protocols: all
      anycastPrefix: jms.queue.
  connectors:
    - port: 61616
      expose: true
      host: amq-mtl-hdls-svc.amq-mtl.svc.cluster.local
      name: amq-mtl-connector
      type: tcp
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
    initImage: quay.io/kepaso/amq-lvl:0.0.13
  console:
    expose: true
  adminUser: admin

---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: demo1
  namespace: amq-lvl
spec:
  addressName: demo1
  queueName: demo1
  routingType: anycast

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: amq-lvl
spec:
  to:
    kind: Service
    name: amq-lvl-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None