apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-ha

resources:
  - amq-consumer-0.yaml
  - amq-consumer-1.yaml
  - amq-consumer-2.yaml
  - amq-producer-0.yaml
  - amq-producer-1.yaml
  - amq-producer-2.yaml