apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  namespace: amq-ha
  name: amq-ha
  application: amq-ha
spec:
  acceptors:
    - port: 61616
      verifyHost: false
      expose: true
      multicastPrefix: jms.topic.
      name: all
      connectionsAllowed: 10
      protocols: all
      anycastPrefix: jms.queue.
  connectors:
    - port: 61616
      expose: true
      host: amq-mtl-hdls-svc.amq-mtl.svc.cluster.local
      name: amq-mtl-connector
      type: tcp
  adminPassword: admin
  deploymentPlan:
    size: 3
    persistenceEnabled: true
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  console:
    expose: true
  adminUser: admin

---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: demo
  namespace: amq-ha
spec:
  addressName: demo
  queueName: demo
  routingType: anycast


# ---
# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: console
#   namespace: amq-ha
# spec:
#   to:
#     kind: Service
#     name: amq-ha-hdls-svc
#     weight: 100
#   port:
#     targetPort: console-jolokia
#   wildcardPolicy: None