apiVersion: v1
kind: Namespace
metadata:
  name: amq-mtl
spec:
  finalizers:
  - kubernetes

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-broker-rhel8
  namespace: amq-mtl
spec:
  targetNamespaces:
  - amq-mtl

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/amq-mtl/subscriptions/amq-broker-rhel8
  name: amq-broker-rhel8
  namespace: amq-mtl
  labels:
    operators.coreos.com/amq-broker-rhel8.amq-mtl: ''
spec:
  channel: 7.x
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v7.8.1-opr-4-rhel8
