# ---
# apiVersion: operators.coreos.com/v1
# kind: OperatorGroup
# metadata:
#   name: amq-broker-rhel8
#   namespace: openshift-operators
# spec:
#   targetNamespaces:
#   - amq-lvl


---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel8
  namespace: openshift-operators
  labels:
    operators.coreos.com/amq-broker-rhel8.amq-lvl: ''
spec:
  channel: 7.10.x
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace